### PR TITLE
Provide a router using pattern matching

### PR DESCRIPTION
**Pull request by mcollina**
cc @lucamaraschi

### CODE REVIEW

**Comment by lucamaraschi** [comment]
👍  LGTM

Personal note is on the usage of an object with a property 'cmd' to indicate the fullname of the rpc destination (aka the function to call), while I would declare it primarily using a string and give the option to the consumer to specify an object instead.

**Comment by mcollina** [comment]
Are you still ok to use `cmd: 'func'` when sending the request? I'm fine with supporting strings as shortcuts. @mcdonnelldean and I were thinking of doing a lightweight https://www.npmjs.com/package/jsonic, that just supports `'a:b,c:d'` things (with no recursion).

The idea for adding more properties (and do full pattern matching) is to support namespacing (´ns: 'pubsub' as an example), version numbers and so forth.

**Comment by lucamaraschi** [comment]
But using string you still would be perfectly able to support multiple level namespacing while versioning should be still explicit, even if I doubt on the use of multiple versions in a single node.

When sending the request I think we should still support primarily the use of strings and have the fallback on the object (imagine the string usage as a shortcut to compose the request object with 'cmd' and 'ns')

**Comment by mcollina** [comment]
Something like:

```js
upring.add('hello', (req, reply) => {
  reply(null, { hello: 'world' })
})
```

and

```js
instance.request({
  cmd: 'hello'
}, console.log)
```

I really care about passing a single object to `request`, as _optionally_ support multiple properties in add. I do not want applications to force a `myservice.hello` notation to namespace things, and I imagine providing to provide some standard services (queue, pubsub, k/v, discovery, circuit breaker) on top of the upring.

**Comment by lucamaraschi** [comment]
Why not a `myservice.hello` notation?I agree on keeping the object notation open and a way to extend the request (even if I still consider it the primary type of the interface having the string as a shortcut) but I still see it boilerplated ;-)

**Comment by mcollina** [comment]
My experience with strings is that it makes them hard to extend, and _when_ you need an object the change cost too much.
I'm actually fine even with the `a.b` notation, if it gets compiled to `{ ns: 'a', cmd: 'b' }`.

As long it's sugar on the interface and all the messages are wrapped into single object that contains cmd and the payload, I'm good.

Do you think we should also update the `request()`  command to a three argument form? Seneca has that.

Something like:

```js
upring.request('hello', {
  value: 'world'
}, console.log)
```

@mcdonnelldean @davidmarkclements any opinions on this?

**Comment by mcdonnelldean** [comment]
I still think you are better off with the `key:value` notation, simply because it's enough expressive to handle 90% of all use cases, eg, `task:merge,options:{cache:false}`

**Comment by mcollina** [comment]
@mcdonnelldean that will likely never be supported here, due to the high steep price of evaluating netsted objects. Something like `task:merge,cache:false` should be easy enough to parse fast.

**Comment by mcdonnelldean** [comment]
@mcollina I would be a little careful about fast vs easy. Fast is great but not at the expensive of easy and I don't think a single level of depth is so slow that the average user cares. 

Anyway, it's something that could be bikeshedded later. The point being I find the `k:v` format more expressive as dots would end up being `task.merge.cache.false` which seems a little icky.

**Comment by lucamaraschi** [comment]
@mcollina I agree with the "compilation" step as the string just wanna be a syntactic sugar for that.
@mcdonnelldean I think the point is how to express the action/cmd notation considering that it might belong to a namespace, while I agree completely with you on the `k:v` notation for options or metadata of that `cmd`

**Comment by lucamaraschi** [comment]
For example in [virgilio](https://github.com/icemobilelab/virgilio) we took this approach expressing `action`s as fullnamespaced and options as a simple `k:v`.

@mcollina I think the API of `request()` should support both 2 and 3 arguments to give the flexibility of expression that the developer wants.

**Comment by mcdonnelldean** [comment]
@lucamaraschi It tend to use `k:v` notation for namespacing but I instead namespace as role/cmd so mine would look like `role:worker,cmd:foo`. The reasoning for this pattern was because it made `role:worker,cmd:foo,customer:specific` easier to namespace out.

Ultimately, I don't want to bikeshed on this though. I mean the parser should be a reasonable place to pop an extension point anyway so the particular parser shouldn't really matter.

**Comment by mcollina** [comment]
I'm merging as is, and moving this discussion to a future time _when we will have actual developers to make __happy___

**Pull request merged**
